/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Crrypto.gltf --transform 
Files: Crrypto.gltf [3.14MB] > C:\Users\91955\Downloads\pi_network_crypto_coin\Crrypto-transformed.glb [430.66KB] (86%)
Author: KennyT (https://sketchfab.com/kennyt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pi-network-crypto-coin-ad550230f87d499fb33a6786eff97bb7
Title: Pi Network Crypto Coin
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/Crrypto-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object011__0.geometry}
        material={materials["Scene_-_Root"]}
        position={[55.838, 1.616, -36.461]}
        rotation={[Math.PI, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Crrypto-transformed.glb");
