/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 farm.gltf --transform 
Files: farm.gltf [6.59MB] > C:\Users\91955\Downloads\middle_age_serf_farm\farm-transformed.glb [1.31MB] (80%)
Author: Skodvirr (https://sketchfab.com/skodvirr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/middle-age-serf-farm-97405d0a09e0408eaba04e6c68bfc655
Title: Middle Age Serf Farm
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/farm-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        position={[106.198, -1.886, -58.526]}
        rotation={[-Math.PI, -0.566, -2.681]}
        scale={[0.085, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_131.geometry}
        material={materials.PaletteMaterial002}
        position={[-26.667, -0.873, 64.201]}
      />
      <mesh
        geometry={nodes.Object_902.geometry}
        material={materials.PaletteMaterial003}
        position={[118.213, -1.435, 60.461]}
      />
      <instancedMesh
        args={[nodes.Object_73.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.Object_73.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_116.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.Object_116.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_147.geometry, materials.PaletteMaterial001, 16]}
        instanceMatrix={nodes.Object_147.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_156.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.Object_156.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_175.geometry, materials.PaletteMaterial001, 14]}
        instanceMatrix={nodes.Object_175.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_183.geometry, materials.PaletteMaterial001, 6]}
        instanceMatrix={nodes.Object_183.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_200.geometry, materials.PaletteMaterial001, 8]}
        instanceMatrix={nodes.Object_200.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_264.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.Object_264.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_309.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.Object_309.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_326.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.Object_326.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_327.geometry, materials.PaletteMaterial001, 5]}
        instanceMatrix={nodes.Object_327.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_356.geometry, materials.PaletteMaterial001, 9]}
        instanceMatrix={nodes.Object_356.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_456.geometry, materials.PaletteMaterial001, 9]}
        instanceMatrix={nodes.Object_456.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_457.geometry, materials.PaletteMaterial001, 9]}
        instanceMatrix={nodes.Object_457.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_472.geometry, materials.PaletteMaterial001, 6]}
        instanceMatrix={nodes.Object_472.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_473.geometry, materials.PaletteMaterial001, 6]}
        instanceMatrix={nodes.Object_473.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Object_600.geometry, materials.PaletteMaterial001, 292]}
        instanceMatrix={nodes.Object_600.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/farm-transformed.glb");
