/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 house.gltf --transform 
Files: house.gltf [23.33MB] > C:\Users\91955\Downloads\final_house\house-transformed.glb [382.37KB] (98%)
Author: Anton Revutsky (https://sketchfab.com/anton.revutsky)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/final-house-20ea8edb2b7043b1a98a0b6ae18684bb
Title: Final House
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/house-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Object029_Material_#2125644136_0"].geometry}
        material={materials.Material_2125644136}
        position={[1.568, 0, -0.154]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.154, 0.154, 0.149]}
      />
      <mesh
        geometry={nodes.Object030_CRNcgaxis_models_46_14_03_0.geometry}
        material={materials["CRN.cgaxis_models_46_14_03"]}
        position={[1.568, 0, -0.154]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.154, 0.154, 0.149]}
      />
      <mesh
        geometry={nodes.Object030_CRNcgaxis_models_46_15_03_0.geometry}
        material={materials["CRN.cgaxis_models_46_15_03"]}
        position={[1.568, 0, -0.154]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.154, 0.154, 0.149]}
      />
      <mesh
        geometry={nodes.Object030_CRNSolid_Glass_0.geometry}
        material={materials["CRN.Solid_Glass"]}
        position={[1.568, 0, -0.154]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.154, 0.154, 0.149]}
      />
      <mesh
        geometry={nodes["Line017_Material_#2125644137_0"].geometry}
        material={materials.Material_2125644137}
        position={[5.886, 0.657, -1.668]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.025}
      />
    </group>
  );
}

useGLTF.preload("/house-transformed.glb");
